application: cds-polymer
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /contacts/(all|favorites|circles)
  static_files: dist/index.html
  upload: dist/index.html

- url: /add
  static_files: dist/index.html
  upload: dist/index.html

- url: /(.*)
  static_files: dist/\1
  upload: dist/.*

skip_files:
- ^(.*/)?node_modules/.*
